if(${PROJECT_NAME}_ENABLE_CONAN)
  #
  # Declare the Conan packages here.
  #
  list(APPEND CONAN_CMAKE_PACKAGES
      opencv/4.5.5
  )

  #
  # Declare the Conan options here.
  #
  list(APPEND CONAN_CMAKE_OPTIONS opencv:shared=True)
  # The OpenCV recipe only defines the `with_gtk` option on Linux.
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    list(APPEND CONAN_CMAKE_OPTIONS opencv:with_gtk=False)
  endif()

  #
  # If `conan.cmake` (from https://github.com/conan-io/cmake-conan) does not exist, download it.
  # Tag 0.18.1 is the latest release of the Conan 1 cmake wrapper, whose recommended flow is
  # conan_cmake_configure() -> conan_cmake_autodetect() -> conan_cmake_install().
  # All Conan generated files live under ${CMAKE_BINARY_DIR}/conan.
  #
  file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/conan")
  if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan/conan.cmake")
    message(
      STATUS
      "Downloading conan.cmake v0.18.1 from https://github.com/conan-io/cmake-conan..."
    )
    file(
      DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/0.18.1/conan.cmake"
      "${CMAKE_BINARY_DIR}/conan/conan.cmake"
      TLS_VERIFY ON
    )
    message(STATUS "cmake-conan downloaded successfully.")
  endif()
  include(${CMAKE_BINARY_DIR}/conan/conan.cmake)

  #
  # This cmake-conan integration and the cmake_find_package generator target Conan 1.
  #
  conan_check(REQUIRED DETECT_QUIET)
  if(CONAN_DETECTED_VERSION VERSION_GREATER_EQUAL 2.0.0)
    message(
      FATAL_ERROR
      "visionlab uses the Conan 1 cmake-conan integration, but Conan ${CONAN_DETECTED_VERSION} "
      "was found. Install Conan 1, for example: pip install 'conan<2'."
    )
  endif()

  #
  # Make the Find*.cmake modules generated by Conan discoverable by find_package().
  #
  list(APPEND CMAKE_MODULE_PATH "${CMAKE_BINARY_DIR}/conan")
  list(APPEND CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}/conan")

  #
  # Ensure the project C++ standard is part of the auto-detected Conan settings.
  #
  set(CMAKE_CXX_STANDARD 17)

  #
  # Current cmake-conan flow. conan_cmake_configure() writes a temporary conanfile.txt into
  # the build directory, then conan_cmake_install() runs `conan install` on it.
  #
  conan_cmake_configure(
    REQUIRES ${CONAN_CMAKE_PACKAGES}
    OPTIONS ${CONAN_CMAKE_OPTIONS}
    GENERATORS cmake_find_package
  )

  conan_cmake_autodetect(settings)

  # The OpenCV 4.5.5 prebuilt binaries on Conan Center were built without an
  # explicit cppstd setting; the project already enforces C++17 through CMake.
  if(WIN32)
    list(FILTER settings EXCLUDE REGEX "^compiler.cppstd=")
  endif()

  conan_cmake_install(
    PATH_OR_REFERENCE .
    BUILD missing
    REMOTE conancenter
    SETTINGS ${settings}
    INSTALL_FOLDER "${CMAKE_BINARY_DIR}/conan"
  )

  #
  # conan_cmake_configure() writes a temporary conanfile.txt into the build root;
  # move it into build/conan afterwards so all Conan artifacts stay together.
  #
  file(REMOVE "${CMAKE_BINARY_DIR}/conan/conanfile.txt")
  file(RENAME "${CMAKE_BINARY_DIR}/conanfile.txt" "${CMAKE_BINARY_DIR}/conan/conanfile.txt")


  find_package(OpenCV REQUIRED)

  verbose_message("Conan setup complete: ${CONAN_CMAKE_PACKAGES} installed.")
endif()
