name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:

    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v4

    - name: cache Conan
      uses: actions/cache@v4
      with:
        path: ~/.conan
        key: ${{ runner.os }}-conan-${{ hashFiles('cmake/Conan.cmake') }}
        restore-keys: |
          ${{ runner.os }}-conan-

    - name: install Conan 1
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --break-system-packages conan==1.65.0

    - name: install Conan system requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y libva-dev libvdpau-dev libx11-dev libx11-xcb-dev libfontenc-dev libice-dev \
          libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev \
          libxdmcp-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev \
          libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev \
          libxss-dev libxt-dev libxtst-dev libxv-dev libxxf86vm-dev libxcb-glx0-dev \
          libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev \
          libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev \
          libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev uuid-dev \
          libxcb-cursor-dev libxcb-dri2-0-dev libxcb-present-dev libxcb-composite0-dev \
          libxcb-ewmh-dev libxcb-res0-dev libxcb-util-dev

    - name: configure Conan remote
      run: conan remote update conancenter https://center.conan.io || true
      
    - name: cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies-${{ hashFiles('CMakeLists.txt') }}

    - name: install GoogleTest
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: |
        cd ..
        git clone https://github.com/google/googletest.git --branch v1.17.0
        cd googletest
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION
        cmake --build build --config Release
        cmake --build build --target install --config Release

    - name: configure
      run: cmake --preset release -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION -Dvisionlab_ENABLE_CODE_COVERAGE=1
      
    - name: build
      run: cmake --build --preset release

    - name: run tests
      run: |
        cd build-release
        ctest -C $BUILD_TYPE -VV

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false

    - name: install project
      run: cmake --build build-release --target install --config Release 
