name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: ".local"

jobs:
  build:

    runs-on: windows-2019
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v4

    - name: cache Conan
      uses: actions/cache@v4
      with:
        path: C:/Users/runneradmin/.conan
        key: ${{ runner.os }}-conan-${{ hashFiles('cmake/Conan.cmake') }}
        restore-keys: |
          ${{ runner.os }}-conan-

    - name: install Conan 1
      run: python -m pip install --break-system-packages conan==1.65.0

    - name: configure Conan remote
      run: conan remote update conancenter https://center.conan.io || true

    - name: cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies-${{ hashFiles('CMakeLists.txt') }}

    - name: install GoogleTest
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: |
        cd ..
        git clone https://github.com/google/googletest.git --branch v1.17.0
        cd googletest
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX="$env:GITHUB_WORKSPACE/$env:INSTALL_LOCATION" -Dgtest_force_shared_crt=1
        cmake --build build --config Release
        cmake --build build --target install --config Release

    - name: configure
      run: cmake --preset release "-DCMAKE_INSTALL_PREFIX=$env:GITHUB_WORKSPACE/$env:INSTALL_LOCATION" -G "Visual Studio 16 2019" -A x64
      
    - name: build
      run: cmake --build --preset release --config Release

    - name: run tests
      run: |
        cd build-release
        ctest -C "$env:BUILD_TYPE" -VV

    - name: install project
      run: cmake --build build-release --target install --config Release 
